server: 
  port: 8081

# DB
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG

mybatis:
  configuration:
    map-underscore-to-camel-case: true